name: hello-world
on: push
jobs: 
  hello-world-job:
    runs-on: ubuntu-latest
    steps: 
      - name: Check out repository code
        uses: actions/checkout@v4
      # - name: say hello world with echo
      - run: echo "$(cat hello_world.txt)"
      - name: other commands
        run: |
          pwd
          ls
          
